{{- if .Values.auth.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: oracle-operator-api-key
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  api-key: {{ .Values.auth.apiKey | quote }}
{{- end }}
