apiVersion: v1
kind: Service
metadata:
  name: oracle-operator-webhook
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "oracle-operator.labels" . | nindent 4 }}
spec:
  selector:
    app: oracle-operator
  ports:
    - port: 9443
      targetPort: 9443
      name: webhook
