---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-oracle-dboperator-io-v1alpha1-oracledatabase
  failurePolicy: Fail
  name: voracledatabase-v1alpha1.kb.io
  rules:
  - apiGroups:
    - oracle.dboperator.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oracledatabases
  sideEffects: None
