apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: oracle-operator-validating-webhook
webhooks:
  - name: voracledatabase-v1alpha1.kb.io
    admissionReviewVersions: ["v1"]
    clientConfig:
      url: "https://127.0.0.1:9443/validate-oracle-dboperator-io-v1alpha1-oracledatabase"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRVENDQWltZ0F3SUJBZ0lVWCtrZ3JQRVdibThIZ1liQnl6emdOSWliZWVJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lqRWdNQjRHQTFVRUF3d1hiM0poWTJ4bExXOXdaWEpoZEc5eUxYZGxZbWh2YjJzd0hoY05Nall3TmpNdwpNRGt5TlRBeVdoY05Nell3TmpJM01Ea3lOVEF5V2pBaU1TQXdIZ1lEVlFRRERCZHZjbUZqYkdVdGIzQmxjbUYwCmIzSXRkMlZpYUc5dmF6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU5zRzBtS1cKbGh0M0liUWlhOFdJOURkRlZueWtKWWVHMXFQd1JpamFBRVZvcVpUQ0gyU0N3N1NkK1UrNUdtTFhpcmUxMmJ1NgpyeGYxdjk1SWJHV20vUUk0NWM5N2xWUnF4NmtGbzcreFRHR1ZKUVZuNWxGUC9rOEJ4dG5pb3MrL3hZZXUxdk44ClRJVlVlb3BYazA2VkExRE53OE5FdU1CSkhoM2l0YUIwbEg5S0tFYjNQbnpJd0hKSXJyZHRwTmdneTlzWCtCWXgKMDczYWV3WXdUR0xEVGd0QXhVR2pMRHBPT1BHVW5kRTZYQ2lWRzNjbnQzVm5IVXJvaXU5UzJjU0dNRk9TZHdtQgpGQ0dVdlRJSU1nSnM0Qng3cHdOaGFpbWJWWXV6ZkxzbHFyTHgwcS9aMmZQcisvNHpUZXErWUNTTkEzUVpWSmsyCjhETGJERWRlZmg2MHl4TUNBd0VBQWFOdk1HMHdIUVlEVlIwT0JCWUVGQlREbFVhczdGR1RTUlNSWUdTeXdsS3EKOHV1ME1COEdBMVVkSXdRWU1CYUFGQlREbFVhczdGR1RTUlNSWUdTeXdsS3E4dXUwTUE4R0ExVWRFd0VCL3dRRgpNQU1CQWY4d0dnWURWUjBSQkJNd0VZY0Vmd0FBQVlJSmJHOWpZV3hvYjNOME1BMEdDU3FHU0liM0RRRUJDd1VBCkE0SUJBUURPRUFtS0J0Qkw4T3NlMUFjREFidmQwd3BZN0MxOUNlZU5NQ0hrQkFZNUFNbGtUNWxqdWMrd0ZuQUgKOEEyZHRHQ29MZVNnRmJBRnRIVlMza3AxcW05aVFvRnlvVHRsVytiQ3NSZVo3T25RZkwrWXRTSzhzZ0l4aVEzRwpqeGtKNU1pYVVod1BkdXB1ZXNIWFQwZ1p6MGVNYXR6YWlPcVFsSUFKVFZjbUxKWTA2STZpZURuRGJSRVkzWFpXCnVMTnR2VlFHYU5zUTBFMld4WWR1bGVxMHVJQTJFNEN3TmgrMGpta2lpUGtlNnh0eW1KUERDTmgzaUVlVEJLTGYKUzBER0d0VXI1cVIwZ3RnRHFTTU5ZQmxuaGpIT1M4RHdiTXQzREJCZXRJd2UyT0JXYXB5ZzQ3WWpmTVRWMTZVeApVL1BNeGZnRmwwR0xtQmxLbXcyYzhuQzFvV3ZGCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - apiGroups: ["oracle.dboperator.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["oracledatabases"]
    sideEffects: None
    failurePolicy: Fail
